dubture_f_fmpeg:
  ffmpeg_binary: /opt/homebrew/bin/ffmpeg
  ffprobe_binary: /opt/homebrew/bin/ffprobe
  binary_timeout: 300 # Use 0 for infinite
  threads_count: 4
  temporary_directory: "%kernel.cache_dir%/ffmpeg"
